config/routes.rb
Rails.application.routes.draw do

  resources :posts do
  member do
    post 'upvote'
    delete 'downvote'
  end
end

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base

    validates :name, uniqueness: true, presence: true
    validates :description, presence: true

    has_many :votes, dependent: :destroy

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def set_post
    @post = Post.find(params[:id])
  end

  def upvote
    @posts = Post.find(params[:id])
    @posts.votes.create
    redirect_to(posts_path)
  end

  def downvote
    @posts = Post.find(params[:id])
    @posts.votes.last.destroy
    redirect_to(posts_path)
  end


  def index
      unorganized_list_of_posts = Post.all
      @posts = unorganized_list_of_posts.sort_by{|post| -post.votes.count }
  end

  def edit
  end

  def show
    @posts = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    end
  end


  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def post_params
    params.require(:post).permit(:name, :description, :photo, :dirurl)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Breddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<ul class="nav nav-tabs">
<li role="presentation" class="active"><a href="/">Home</a></li>
<li role="presentation"><a href="#">Profile</a></li>
<li role="presentation"><a href="#">Messages</a></li>
</ul>



<body>



<%= yield %>

</body>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="panel panel-default">
  <div class="panel-body">

  </div>
  <div class="panel-footer">Breddit.com | 2015 </div>
</div>

</html>

app/views/posts/_form.html.erb
<div class="container">
  <%= simple_form_for @post do |f| %>
    <%= f.input :name, label: 'title' %>
    <%= f.input :dirurl, label: 'url', :input_html => { :value => 'http://' } %>
    <%= f.input :photo, label: 'image link', :input_html => { :value => 'http://' } %>
    <%= f.input :description, :cols => 70, :rows => 30 %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="page-header">
  <h1><span class="glyphicon glyphicon-tree-conifer" aria-hidden="true"></span>Breddit <small>edit post</small></h1>
<br>
</div>
<div class="container">
  <%= simple_form_for @post do |f| %>

    <%= f.input :name, label: 'title', as: :url %>
    <%= f.input :dirurl, label: 'url', :input_html => { :value => 'http://' } %>
    <%= f.input :photo, label: 'image link' %>
    <%= f.input :description, :cols => 70, :rows => 30 %>
    <%= f.button :submit %>
  <% end %>
</div>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="page-header">
  <h1><span class="glyphicon glyphicon-tree-conifer" aria-hidden="true"></span>Breddit <small>functionality absent (even when working)</small></h1>
<br>
</div>

<div class="container">
  <button class="btn btn-default"><%= link_to 'New Post', new_post_path %></button>
  <% @posts.each do |post| %>
    <div class="media"></div>
    <div class="upv">
      <div class="media-left media-top">
      <%= button_to upvote_post_path(post), method: :post, class: "btn btn-primary btn-xs" do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
      <% end %>
      <p> <%= post.votes.count %> </p>
      <%= button_to downvote_post_path(post), method: :delete, class: "btn btn-primary btn-xs" do %>
        <span class="glyphicon glyphicon-chevron-down"></span>
      <% end %>
    </div>
    <div class="media-left media-top">
      <%= image_tag post.photo, class: "img-thumbnail" %>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= link_to post.name, post.dirurl %></h4>
        <small>submitted <%= link_to post.created_at.to_s(:long), post %></small>
      <p> <%= truncate post.description, length: 400 %> </p>
      <small>1540 comments share</small>
    </div>
   </div>
  <%end%>
  <hr>
</div>

app/views/posts/new.html.erb
<div class="page-header">
  <h1><span class="glyphicon glyphicon-tree-conifer" aria-hidden="true"></span>Breddit <small>new link</small></h1>
<br>
</div>
<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="page-header">
  <h1><%= link_to @posts.name, @posts.dirurl %> <small>(external link)</small></h1>

  <%= image_tag @posts.photo, class: "img-thumbnail" %>

</div>

<div class="panel panel-default">
  <div class="panel-body">
    <%= simple_format @posts.description %>

  </div>
</div>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' } %> |
<%= link_to 'Back', posts_path %>